[package]
name = "habitron"
version = "0.1.0"
authors = ["Tejas Mahajan"]
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

